### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an index.html file and add an HTML skeleton
- [x] Create a styles.css file and link it to index.html
- [x] Add the image of the car to the HTML
- [x] Change background color to match example
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Fix all errors

## Example

This is just an example in case you need it.

![user can see their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-see-their-car.png)
