### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a  main.js file and link it to index.html
- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west)
- [x] Create classes to change direction of car with transform property
- [x] Listen for 'keydown' events on the document to change direction
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Fix all errors

## Example

This is just an example in case you need it.

![user can turn their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-turn-their-car.gif)
