### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started
- [x] Create a stopCar function and integrate with the handleMovement function
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Fix all errors

## Example

This is just an example in case you need it.

![user can stop their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-stop-their-car.gif)
