### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update the startCar function to move based on the currentDirection value of your data model
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Fix all errors

## Example

This is just an example in case you need it.

![user can steer their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-steer-their-car.gif)
